### ISSUE TITLE
Still Broken 

### ISSUE THREAD

**Issue by ContegoCode** [tamnguyenvan/malnet#6]
Hello again I am unable to run create_data.py. I have followed the instructions step by step and have uninstalled python and started completely fresh but get this error:

 self._popen = self._Popen(self)
  File "C:\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

It will output .dat files as described but the Vectoring doesn't complete and training.py  is the same output and just continues on a infinite loop. I am running python 3.68 with no luck so i started fresh install again with python 3.5.4 and followed the instructions once again. There seems to be a issue when trying to pip install pkg-resources==0.0.0 and also pandas ==1.0.1 so i installed pandas 0.25.3 without any errors. I'm running windows 10 please help

**Comment by tamnguyenvan** [comment]
I'm pretty sure that Windows is the problem. You need to wrap the code by an ```if __name__ == '__main__'``` as follows:
```python
if __name__ == '__main__':
    ember.create_vectorized_features(data_dir, scale=args.scale)
````

**Comment by ContegoCode** [comment]
Thank you again for your reply and your patients. What you have suggested worked perfectly and I was able to fully train the model. I tried to test it with the test.py command against a virus file and received a output ”Threshold: 0.273000” but also got a error under it that reads

Loading model from C:\Users \Desktop\malnet-master\malnet\saved_models
Traceback (most recent call last):
  File "test.py", line 55, in <module>
    with open(scaler_path, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

Im sure once this is resolved everything should work as expected!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tamnguyenvan** [comment]
Hi, It's my fault. You need to provide an additional option in test command: `--scaler_path /path/to/scaler_file`, where `scaler file` is the file that was saved in the training phase. It's default place is the same as the model directory. It should be right there. In case you concerned what exactly that file is, it's just a  pickle file that contains a scikit-learn StandardScaler object for our data normalization.
I will update file README.md soon. Any contribution is welcome.

**Comment by ContegoCode** [comment]
Sorry still no luck I tried to enter the test.py command like so

test.py --input_file "C:\Users\ Desktop\PDFXCview.exe" --model_path "C:\Users\ Desktop\malnet-master\malnet\saved_models" --scaler_path "C:\Users\ Desktop\malnet-master\malnet\saved_models"

the model files created and the scaler.pkl file is all in that directory

I still get the error output that says test.py line 55 TypeError: expected str, bytes or os.PathLike object, not NoneType
And now I also get another error PermissionError: [Errno 13] Permission denied: 'C:\\Users \\Desktop\\Trained'

I am running my CMD windows as administrator and full control of the file permissions is checked what am I doing wrong?..

**Comment by ContegoCode** [comment]
Here is a full CMD output from the command

C:\Users\ Desktop\malnet-master\malnet>test.py --input_file "C:\Users\Cobal\Desktop\PDFXCview.exe" --model_path "C:\Users\Cobal\Desktop\Trained" --scaler_path "C:\Users\ Desktop\Trained"
Using TensorFlow backend.
2020-03-20 04:16:04.376705: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-03-20 04:16:04.380562: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From C:\Users\ Desktop\malnet-master\malnet\test.py:20: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From C:\Users\Cobal\Desktop\malnet-master\malnet\test.py:22: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-03-20 04:16:08.203844: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-03-20 04:16:08.209654: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-03-20 04:16:08.400060: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
2020-03-20 04:16:08.404903: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:02:00.0
2020-03-20 04:16:08.411873: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-03-20 04:16:08.417878: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cublas64_100.dll'; dlerror: cublas64_100.dll not found
2020-03-20 04:16:08.424093: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cufft64_100.dll'; dlerror: cufft64_100.dll not found
2020-03-20 04:16:08.430420: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'curand64_100.dll'; dlerror: curand64_100.dll not found
2020-03-20 04:16:08.436427: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusolver64_100.dll'; dlerror: cusolver64_100.dll not found
2020-03-20 04:16:08.442475: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusparse64_100.dll'; dlerror: cusparse64_100.dll not found
2020-03-20 04:16:08.458657: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-03-20 04:16:08.462204: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-03-20 04:16:08.473257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-20 04:16:08.476456: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1
2020-03-20 04:16:08.478557: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N N
2020-03-20 04:16:08.480597: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   N N
Example: C:\Users\Cobal\Desktop\PDFXCview.exe
Model path: C:\Users\Cobal\Desktop\Trained
Threshold: 0.273000
Loading model from C:\Users\ Desktop\Trained
Traceback (most recent call last):
  File "C:\Users\ Desktop\malnet-master\malnet\test.py", line 55, in <module>
    with open(scaler_path, 'rb') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ Desktop\\Trained'



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tamnguyenvan** [comment]
You mised the filename. It should be `the/directory/scaler.pkl'. See `test.py` for more details.

**Comment by ContegoCode** [comment]
My apologies here is the new output


C:\Users\Cobal\Desktop\malnet-master\malnet>python test.py --input_file C:\Users\Cobal\Desktop\PDFXCview.exe --model_path C:\Users\Cobal\Desktop\malnet-master\malnet\saved_models --scaler_path C:\Users\Cobal\Desktop\malnet-master\malnet\saved_models\scaler.pkl
Using TensorFlow backend.
2020-03-20 04:27:02.779247: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-03-20 04:27:02.784036: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From test.py:20: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From test.py:22: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-03-20 04:27:06.588369: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-03-20 04:27:06.593948: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-03-20 04:27:06.780543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
2020-03-20 04:27:06.785303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:02:00.0
2020-03-20 04:27:06.792289: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-03-20 04:27:06.798200: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cublas64_100.dll'; dlerror: cublas64_100.dll not found
2020-03-20 04:27:06.804220: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cufft64_100.dll'; dlerror: cufft64_100.dll not found
2020-03-20 04:27:06.810240: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'curand64_100.dll'; dlerror: curand64_100.dll not found
2020-03-20 04:27:06.816242: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusolver64_100.dll'; dlerror: cusolver64_100.dll not found
2020-03-20 04:27:06.822204: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusparse64_100.dll'; dlerror: cusparse64_100.dll not found
2020-03-20 04:27:06.836100: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-03-20 04:27:06.839224: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-03-20 04:27:06.847760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-20 04:27:06.850920: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1
2020-03-20 04:27:06.853247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N N
2020-03-20 04:27:06.855249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   N N
Example: C:\Users\Cobal\Desktop\PDFXCview.exe
Model path: C:\Users\Cobal\Desktop\malnet-master\malnet\saved_models
Threshold: 0.273000
Loading model from C:\Users\Cobal\Desktop\malnet-master\malnet\saved_models
Traceback (most recent call last):
  File "test.py", line 57, in <module>
    model = load_model(model_path)
  File "C:\Program Files\Python36\lib\site-packages\keras\models.py", line 233, in load_model
    with h5py.File(filepath, mode='r') as f:
  File "C:\Program Files\Python36\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "C:\Program Files\Python36\lib\site-packages\h5py\_hl\files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'C:\Users\Cobal\Desktop\malnet-master\malnet\saved_models', errno = 13, error message = 'Permission denied', flags = 0, o_flags = 0)


Any Ideas??? Omg im ripping my hair out lmao

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ContegoCode** [comment]
I was able to fix the file permission denied with a simple backslash but I still get this

C:\Users\Cobal\Desktop\malnet-master\malnet>python test.py --input_file "C:\Users\Cobal\Desktop\PDFXCview.exe" --model_path "C:\Users\Cobal\Desktop\malnet-master\malnet\saved_models\" --scaler_path "C:\Users\Cobal\Desktop\malnet-master\malnet\saved_models\scaler.pkl"
Using TensorFlow backend.
2020-03-20 04:34:56.980603: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-03-20 04:34:56.984709: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From test.py:20: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From test.py:22: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-03-20 04:35:00.801495: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-03-20 04:35:00.806985: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-03-20 04:35:01.000614: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
2020-03-20 04:35:01.005372: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:02:00.0
2020-03-20 04:35:01.012293: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-03-20 04:35:01.018164: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cublas64_100.dll'; dlerror: cublas64_100.dll not found
2020-03-20 04:35:01.024310: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cufft64_100.dll'; dlerror: cufft64_100.dll not found
2020-03-20 04:35:01.031098: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'curand64_100.dll'; dlerror: curand64_100.dll not found
2020-03-20 04:35:01.037035: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusolver64_100.dll'; dlerror: cusolver64_100.dll not found
2020-03-20 04:35:01.042891: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusparse64_100.dll'; dlerror: cusparse64_100.dll not found
2020-03-20 04:35:01.056599: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-03-20 04:35:01.059620: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-03-20 04:35:01.068564: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-20 04:35:01.071748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1
2020-03-20 04:35:01.074087: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N N
2020-03-20 04:35:01.076079: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   N N
Example: C:\Users\Cobal\Desktop\PDFXCview.exe
Model path: C:\Users\Cobal\Desktop\malnet-master\malnet\saved_models" --scaler_path C:\Users\Cobal\Desktop\malnet-master\malnet\saved_models\scaler.pkl
Threshold: 0.273000
Loading model from C:\Users\Cobal\Desktop\malnet-master\malnet\saved_models" --scaler_path C:\Users\Cobal\Desktop\malnet-master\malnet\saved_models\scaler.pkl
Traceback (most recent call last):
  File "test.py", line 55, in <module>
    with open(scaler_path, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ContegoCode** [comment]
The error in question now is

Traceback (most recent call last):
  File "test.py", line 55, in <module>
    with open(scaler_path, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tamnguyenvan** [comment]
ok, try this `python test.py --input_file path/to/exe/file --model_path path/to/model/file --scaler_path path/to/scaler/file`. I found that you missed the model file name.

**Comment by ContegoCode** [comment]
YES! OMG YOU’RE A KING SIR!!!!!!!!!!!

IT WORKED PERFECTLY!!!!!!!

I am so sorry and thankful you took the time to work it out with me here is the successful output!!!!!

C:\Users\Cobal\Desktop\malnet-master\malnet>python test.py --input_file "C:\Users\Cobal\Desktop\PDFXCview.exe" --model_path "C:\Users\Cobal\Desktop\malnet-master\malnet\saved_models\malnet_model.003.h5" --scaler_path "C:\Users\Cobal\Desktop\malnet-master\malnet\saved_models\scaler.pkl"
Using TensorFlow backend.
2020-03-20 04:45:24.103464: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-03-20 04:45:24.108321: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From test.py:20: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From test.py:22: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-03-20 04:45:27.929005: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-03-20 04:45:27.934543: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-03-20 04:45:28.144618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
2020-03-20 04:45:28.149535: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:02:00.0
2020-03-20 04:45:28.156444: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-03-20 04:45:28.162304: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cublas64_100.dll'; dlerror: cublas64_100.dll not found
2020-03-20 04:45:28.168500: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cufft64_100.dll'; dlerror: cufft64_100.dll not found
2020-03-20 04:45:28.174465: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'curand64_100.dll'; dlerror: curand64_100.dll not found
2020-03-20 04:45:28.180399: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusolver64_100.dll'; dlerror: cusolver64_100.dll not found
2020-03-20 04:45:28.186532: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusparse64_100.dll'; dlerror: cusparse64_100.dll not found
2020-03-20 04:45:28.200238: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-03-20 04:45:28.203271: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-03-20 04:45:28.211826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-20 04:45:28.215148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1
2020-03-20 04:45:28.217413: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N N
2020-03-20 04:45:28.219471: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   N N
Example: C:\Users\Cobal\Desktop\PDFXCview.exe
Model path: C:\Users\Cobal\Desktop\malnet-master\malnet\saved_models\malnet_model.003.h5
Threshold: 0.273000
Loading model from C:\Users\Cobal\Desktop\malnet-master\malnet\saved_models\malnet_model.003.h5
WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:58: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:442: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:3543: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:1188: calling reduce_sum_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:1205: calling reduce_prod_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:153: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:333: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:341: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\keras\optimizers.py:711: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:2759: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\ops\math_grad.py:1424: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:899: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:625: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:886: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

Score: 0.37549 -> Malicous


BINGO!!!!!!!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tamnguyenvan** [comment]
:+1: Not at all. Your feedback is also a good contribution for this repo. Let me know if you have any idea to improve the code. I will appreciate that.

**Comment by ContegoCode** [comment]
I will for sure examine the code more closely in the future to give any ideas I can

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tamnguyenvan** [comment]
ok, This one should be closed now.
Btw, your GPU hasn't worked yet. I see some errors in the output.
